In [1]:
# Import numpy package
import numpy as np

## array 

In [3]:
# create an array to store single element 10
arr = np.array(10)
print(arr)
print(type(arr)) #return type of array
print(arr.ndim) #return dimension of array


10
<class 'numpy.ndarray'>
0


In [7]:
# to crete 1D array we can use list or tuple

A = [1,2,3,4,5]
print(A)
print(type(A)) #return type of list
print("converting_list_to_array")
arr = np.array(A)
print(arr)
print(type(arr)) #return type of array
print(arr.ndim) #return dimension of array

[1, 2, 3, 4, 5]
<class 'list'>
converting_list_to_array
[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [9]:
# array from tuple

B = tuple(range(1,10))
print(B)
print(type(B)) #return type of tuple
print("converting_tuple_to_array")
arr2 = np.array(B)
print(arr2)
print(type(arr2)) #return type of array
print(arr2.ndim) #return dimension of array


(1, 2, 3, 4, 5, 6, 7, 8, 9)
<class 'tuple'>
converting_tuple_to_array
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


## 2d array (basically matrices which will have rows and columns)
# 2d array are created using nested list or nested tuple

In [11]:
a = [[1,2],[3,4]]
print(a)
print(type(a)) #return type of list
print("converting_list_to_2d_array")
arr3 = np.array(a)
print(arr3) 
print(type(arr3)) #return type of array
print(arr3.ndim) #return dimension of array

[[1, 2], [3, 4]]
<class 'list'>
converting_list_to_2d_array
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


In [13]:
# create a 2d array 

arr4 = np.array([[2,3,7],[4,5,6]])
print(arr4)
print(type(arr4)) #return type of array
print(arr4.ndim) #return dimension of array

[[2 3 7]
 [4 5 6]]
<class 'numpy.ndarray'>
2


Basic functions

• size : It is used to find number of elements in a array

• dtype: To find data type of elements

• type: To find type of object

• shape : It is used to find number of rows and columns
* ndim : dimension of an array


In [16]:
arr = np.array([1,2,3,4,5])
print(arr)
print('Dimension',arr.ndim) #return dimension of array
print("Shape",arr.shape) #return shape of array
print("Size",arr.size) #return size of array
print("Data Type",arr.dtype) #return datatype of array
print("type",type(arr)) #return type of array


[1 2 3 4 5]
Dimension 1
Shape (5,)
Size 5
Data Type int32
type <class 'numpy.ndarray'>


In [18]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print('Dimension',arr_2d.ndim) #return dimension of array
print("Shape",arr_2d.shape) #return shape of array #first element is row and second element is column
print("Size",arr_2d.size) #return size of array
print("Data Type",arr_2d.dtype) #return datatype of array
print("type",type(arr_2d)) #return type of array

[[1 2 3]
 [4 5 6]]
Dimension 2
Shape (2, 3)
Size 6
Data Type int32
type <class 'numpy.ndarray'>


## Basic maths functions
* sum() : sum of the elements.
* mean(): mean of array elements
* median(): median of array elements
* std(): standard deviation of array elements
* min(): mini value of array
* max(): max value of array
* linalg.inv(): inverse of a matrix
* linalg.det(): determinant of the matrix
* linalg.elg(): elgenvalues and elgenvectors of a matrix